# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'M:\Daten\Privat\RaspberryPi\git\RaspberryPylot\gui\MainWindow.ui'
#
# Created: Thu Sep  6 20:29:23 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 640)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_j0 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_j0.setFlat(False)
        self.groupBox_j0.setObjectName(_fromUtf8("groupBox_j0"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_j0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lcdNumber_j_0_a_2 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_a_2.setNumDigits(4)
        self.lcdNumber_j_0_a_2.setObjectName(_fromUtf8("lcdNumber_j_0_a_2"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_a_2, 2, 2, 1, 1)
        self.lcdNumber_j_0_a_3 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_a_3.setNumDigits(4)
        self.lcdNumber_j_0_a_3.setObjectName(_fromUtf8("lcdNumber_j_0_a_3"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_a_3, 2, 3, 1, 1)
        self.lcdNumber_j_0_a_6 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_a_6.setNumDigits(4)
        self.lcdNumber_j_0_a_6.setObjectName(_fromUtf8("lcdNumber_j_0_a_6"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_a_6, 2, 6, 1, 1)
        self.lcdNumber_j_0_a_4 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_a_4.setNumDigits(4)
        self.lcdNumber_j_0_a_4.setObjectName(_fromUtf8("lcdNumber_j_0_a_4"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_a_4, 2, 4, 1, 1)
        self.lcdNumber_j_0_a_0 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_a_0.setNumDigits(4)
        self.lcdNumber_j_0_a_0.setObjectName(_fromUtf8("lcdNumber_j_0_a_0"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_a_0, 2, 0, 1, 1)
        self.label_j_0_a_7 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_a_7.setObjectName(_fromUtf8("label_j_0_a_7"))
        self.gridLayout_2.addWidget(self.label_j_0_a_7, 0, 7, 1, 1)
        self.lcdNumber_j_0_a_1 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_a_1.setNumDigits(4)
        self.lcdNumber_j_0_a_1.setObjectName(_fromUtf8("lcdNumber_j_0_a_1"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_a_1, 2, 1, 1, 1)
        self.lcdNumber_j_0_a_5 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_a_5.setNumDigits(4)
        self.lcdNumber_j_0_a_5.setObjectName(_fromUtf8("lcdNumber_j_0_a_5"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_a_5, 2, 5, 1, 1)
        self.lcdNumber_j_0_a_7 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_a_7.setNumDigits(4)
        self.lcdNumber_j_0_a_7.setObjectName(_fromUtf8("lcdNumber_j_0_a_7"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_a_7, 2, 7, 1, 1)
        self.lcdNumber_j_0_s_0 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_s_0.setNumDigits(4)
        self.lcdNumber_j_0_s_0.setObjectName(_fromUtf8("lcdNumber_j_0_s_0"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_s_0, 5, 0, 1, 1)
        self.lcdNumber_j_0_s_1 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_s_1.setNumDigits(4)
        self.lcdNumber_j_0_s_1.setObjectName(_fromUtf8("lcdNumber_j_0_s_1"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_s_1, 5, 1, 1, 1)
        self.lcdNumber_j_0_s_2 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_s_2.setNumDigits(4)
        self.lcdNumber_j_0_s_2.setObjectName(_fromUtf8("lcdNumber_j_0_s_2"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_s_2, 5, 2, 1, 1)
        self.lcdNumber_j_0_s_3 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_s_3.setNumDigits(4)
        self.lcdNumber_j_0_s_3.setObjectName(_fromUtf8("lcdNumber_j_0_s_3"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_s_3, 5, 3, 1, 1)
        self.lcdNumber_j_0_s_4 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_s_4.setNumDigits(4)
        self.lcdNumber_j_0_s_4.setObjectName(_fromUtf8("lcdNumber_j_0_s_4"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_s_4, 5, 4, 1, 1)
        self.lcdNumber_j_0_s_5 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_s_5.setNumDigits(4)
        self.lcdNumber_j_0_s_5.setObjectName(_fromUtf8("lcdNumber_j_0_s_5"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_s_5, 5, 5, 1, 1)
        self.lcdNumber_j_0_s_6 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_s_6.setNumDigits(4)
        self.lcdNumber_j_0_s_6.setObjectName(_fromUtf8("lcdNumber_j_0_s_6"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_s_6, 5, 6, 1, 1)
        self.lcdNumber_j_0_s_7 = QtGui.QLCDNumber(self.groupBox_j0)
        self.lcdNumber_j_0_s_7.setNumDigits(4)
        self.lcdNumber_j_0_s_7.setObjectName(_fromUtf8("lcdNumber_j_0_s_7"))
        self.gridLayout_2.addWidget(self.lcdNumber_j_0_s_7, 5, 7, 1, 1)
        self.verticalSlider_j_0_a_4 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_a_4.setMinimum(-100)
        self.verticalSlider_j_0_a_4.setMaximum(100)
        self.verticalSlider_j_0_a_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_a_4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_a_4.setTickInterval(25)
        self.verticalSlider_j_0_a_4.setObjectName(_fromUtf8("verticalSlider_j_0_a_4"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_a_4, 1, 4, 1, 1)
        self.verticalSlider_j_0_a_2 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_a_2.setMinimum(-100)
        self.verticalSlider_j_0_a_2.setMaximum(100)
        self.verticalSlider_j_0_a_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_a_2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_a_2.setTickInterval(25)
        self.verticalSlider_j_0_a_2.setObjectName(_fromUtf8("verticalSlider_j_0_a_2"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_a_2, 1, 2, 1, 1)
        self.verticalSlider_j_0_a_3 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_a_3.setMinimum(-100)
        self.verticalSlider_j_0_a_3.setMaximum(100)
        self.verticalSlider_j_0_a_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_a_3.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_a_3.setTickInterval(25)
        self.verticalSlider_j_0_a_3.setObjectName(_fromUtf8("verticalSlider_j_0_a_3"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_a_3, 1, 3, 1, 1)
        self.verticalSlider_j_0_a_7 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_a_7.setMinimum(-100)
        self.verticalSlider_j_0_a_7.setMaximum(100)
        self.verticalSlider_j_0_a_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_a_7.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_a_7.setTickInterval(25)
        self.verticalSlider_j_0_a_7.setObjectName(_fromUtf8("verticalSlider_j_0_a_7"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_a_7, 1, 7, 1, 1)
        self.verticalSlider_j_0_a_6 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_a_6.setMinimum(-100)
        self.verticalSlider_j_0_a_6.setMaximum(100)
        self.verticalSlider_j_0_a_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_a_6.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_a_6.setTickInterval(25)
        self.verticalSlider_j_0_a_6.setObjectName(_fromUtf8("verticalSlider_j_0_a_6"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_a_6, 1, 6, 1, 1)
        self.verticalSlider_j_0_a_0 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_a_0.setMinimum(-100)
        self.verticalSlider_j_0_a_0.setMaximum(100)
        self.verticalSlider_j_0_a_0.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_a_0.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_a_0.setTickInterval(25)
        self.verticalSlider_j_0_a_0.setObjectName(_fromUtf8("verticalSlider_j_0_a_0"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_a_0, 1, 0, 1, 1)
        self.verticalSlider_j_0_a_5 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_a_5.setMinimum(-100)
        self.verticalSlider_j_0_a_5.setMaximum(100)
        self.verticalSlider_j_0_a_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_a_5.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_a_5.setTickInterval(25)
        self.verticalSlider_j_0_a_5.setObjectName(_fromUtf8("verticalSlider_j_0_a_5"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_a_5, 1, 5, 1, 1)
        self.verticalSlider_j_0_a_1 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_a_1.setMinimum(-100)
        self.verticalSlider_j_0_a_1.setMaximum(100)
        self.verticalSlider_j_0_a_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_a_1.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_a_1.setTickInterval(25)
        self.verticalSlider_j_0_a_1.setObjectName(_fromUtf8("verticalSlider_j_0_a_1"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_a_1, 1, 1, 1, 1)
        self.verticalSlider_j_0_s_0 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_s_0.setMinimum(-100)
        self.verticalSlider_j_0_s_0.setMaximum(100)
        self.verticalSlider_j_0_s_0.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_s_0.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_s_0.setTickInterval(25)
        self.verticalSlider_j_0_s_0.setObjectName(_fromUtf8("verticalSlider_j_0_s_0"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_s_0, 4, 0, 1, 1)
        self.verticalSlider_j_0_s_1 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_s_1.setMinimum(-100)
        self.verticalSlider_j_0_s_1.setMaximum(100)
        self.verticalSlider_j_0_s_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_s_1.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_s_1.setTickInterval(25)
        self.verticalSlider_j_0_s_1.setObjectName(_fromUtf8("verticalSlider_j_0_s_1"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_s_1, 4, 1, 1, 1)
        self.verticalSlider_j_0_s_2 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_s_2.setMinimum(-100)
        self.verticalSlider_j_0_s_2.setMaximum(100)
        self.verticalSlider_j_0_s_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_s_2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_s_2.setTickInterval(25)
        self.verticalSlider_j_0_s_2.setObjectName(_fromUtf8("verticalSlider_j_0_s_2"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_s_2, 4, 2, 1, 1)
        self.verticalSlider_j_0_s_3 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_s_3.setMinimum(-100)
        self.verticalSlider_j_0_s_3.setMaximum(100)
        self.verticalSlider_j_0_s_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_s_3.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_s_3.setTickInterval(25)
        self.verticalSlider_j_0_s_3.setObjectName(_fromUtf8("verticalSlider_j_0_s_3"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_s_3, 4, 3, 1, 1)
        self.verticalSlider_j_0_s_4 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_s_4.setMinimum(-100)
        self.verticalSlider_j_0_s_4.setMaximum(100)
        self.verticalSlider_j_0_s_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_s_4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_s_4.setTickInterval(25)
        self.verticalSlider_j_0_s_4.setObjectName(_fromUtf8("verticalSlider_j_0_s_4"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_s_4, 4, 4, 1, 1)
        self.verticalSlider_j_0_s_5 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_s_5.setMinimum(-100)
        self.verticalSlider_j_0_s_5.setMaximum(100)
        self.verticalSlider_j_0_s_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_s_5.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_s_5.setTickInterval(25)
        self.verticalSlider_j_0_s_5.setObjectName(_fromUtf8("verticalSlider_j_0_s_5"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_s_5, 4, 5, 1, 1)
        self.verticalSlider_j_0_s_6 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_s_6.setMinimum(-100)
        self.verticalSlider_j_0_s_6.setMaximum(100)
        self.verticalSlider_j_0_s_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_s_6.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_s_6.setTickInterval(25)
        self.verticalSlider_j_0_s_6.setObjectName(_fromUtf8("verticalSlider_j_0_s_6"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_s_6, 4, 6, 1, 1)
        self.verticalSlider_j_0_s_7 = QtGui.QSlider(self.groupBox_j0)
        self.verticalSlider_j_0_s_7.setMinimum(-100)
        self.verticalSlider_j_0_s_7.setMaximum(100)
        self.verticalSlider_j_0_s_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_0_s_7.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_0_s_7.setTickInterval(25)
        self.verticalSlider_j_0_s_7.setObjectName(_fromUtf8("verticalSlider_j_0_s_7"))
        self.gridLayout_2.addWidget(self.verticalSlider_j_0_s_7, 4, 7, 1, 1)
        self.label_j_0_a_0 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_a_0.setObjectName(_fromUtf8("label_j_0_a_0"))
        self.gridLayout_2.addWidget(self.label_j_0_a_0, 0, 0, 1, 1)
        self.label_j_0_a_1 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_a_1.setObjectName(_fromUtf8("label_j_0_a_1"))
        self.gridLayout_2.addWidget(self.label_j_0_a_1, 0, 1, 1, 1)
        self.label_j_0_a_2 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_a_2.setObjectName(_fromUtf8("label_j_0_a_2"))
        self.gridLayout_2.addWidget(self.label_j_0_a_2, 0, 2, 1, 1)
        self.label_j_0_a_3 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_a_3.setObjectName(_fromUtf8("label_j_0_a_3"))
        self.gridLayout_2.addWidget(self.label_j_0_a_3, 0, 3, 1, 1)
        self.label_j_0_a_4 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_a_4.setObjectName(_fromUtf8("label_j_0_a_4"))
        self.gridLayout_2.addWidget(self.label_j_0_a_4, 0, 4, 1, 1)
        self.label_j_0_a_5 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_a_5.setObjectName(_fromUtf8("label_j_0_a_5"))
        self.gridLayout_2.addWidget(self.label_j_0_a_5, 0, 5, 1, 1)
        self.label_j_0_a_6 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_a_6.setObjectName(_fromUtf8("label_j_0_a_6"))
        self.gridLayout_2.addWidget(self.label_j_0_a_6, 0, 6, 1, 1)
        self.label_j_0_s_0 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_s_0.setObjectName(_fromUtf8("label_j_0_s_0"))
        self.gridLayout_2.addWidget(self.label_j_0_s_0, 3, 0, 1, 1)
        self.label_j_0_s_1 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_s_1.setObjectName(_fromUtf8("label_j_0_s_1"))
        self.gridLayout_2.addWidget(self.label_j_0_s_1, 3, 1, 1, 1)
        self.label_j_0_s_2 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_s_2.setObjectName(_fromUtf8("label_j_0_s_2"))
        self.gridLayout_2.addWidget(self.label_j_0_s_2, 3, 2, 1, 1)
        self.label_j_0_s_3 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_s_3.setObjectName(_fromUtf8("label_j_0_s_3"))
        self.gridLayout_2.addWidget(self.label_j_0_s_3, 3, 3, 1, 1)
        self.label_j_0_s_4 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_s_4.setObjectName(_fromUtf8("label_j_0_s_4"))
        self.gridLayout_2.addWidget(self.label_j_0_s_4, 3, 4, 1, 1)
        self.label_j_0_s_5 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_s_5.setObjectName(_fromUtf8("label_j_0_s_5"))
        self.gridLayout_2.addWidget(self.label_j_0_s_5, 3, 5, 1, 1)
        self.label_j_0_s_6 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_s_6.setObjectName(_fromUtf8("label_j_0_s_6"))
        self.gridLayout_2.addWidget(self.label_j_0_s_6, 3, 6, 1, 1)
        self.label_j_0_s_7 = QtGui.QLabel(self.groupBox_j0)
        self.label_j_0_s_7.setObjectName(_fromUtf8("label_j_0_s_7"))
        self.gridLayout_2.addWidget(self.label_j_0_s_7, 3, 7, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.groupBox_j0, 1, 1, 1, 1)
        self.groupBox_j1 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_j1.setObjectName(_fromUtf8("groupBox_j1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_j1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_j_1_s_5 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_s_5.setObjectName(_fromUtf8("label_j_1_s_5"))
        self.gridLayout_3.addWidget(self.label_j_1_s_5, 3, 5, 1, 1)
        self.label_j_1_s_3 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_s_3.setObjectName(_fromUtf8("label_j_1_s_3"))
        self.gridLayout_3.addWidget(self.label_j_1_s_3, 3, 3, 1, 1)
        self.label_j_1_s_4 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_s_4.setObjectName(_fromUtf8("label_j_1_s_4"))
        self.gridLayout_3.addWidget(self.label_j_1_s_4, 3, 4, 1, 1)
        self.lcdNumber_j_1_a_4 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_a_4.setNumDigits(4)
        self.lcdNumber_j_1_a_4.setObjectName(_fromUtf8("lcdNumber_j_1_a_4"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_a_4, 2, 4, 1, 1)
        self.verticalSlider_j_1_s_0 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_s_0.setMinimum(-100)
        self.verticalSlider_j_1_s_0.setMaximum(100)
        self.verticalSlider_j_1_s_0.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_s_0.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_s_0.setTickInterval(25)
        self.verticalSlider_j_1_s_0.setObjectName(_fromUtf8("verticalSlider_j_1_s_0"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_s_0, 4, 0, 1, 1)
        self.verticalSlider_j_1_a_0 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_a_0.setMinimum(-100)
        self.verticalSlider_j_1_a_0.setMaximum(100)
        self.verticalSlider_j_1_a_0.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_a_0.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_a_0.setTickInterval(25)
        self.verticalSlider_j_1_a_0.setObjectName(_fromUtf8("verticalSlider_j_1_a_0"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_a_0, 1, 0, 1, 1)
        self.label_j_1_s_2 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_s_2.setObjectName(_fromUtf8("label_j_1_s_2"))
        self.gridLayout_3.addWidget(self.label_j_1_s_2, 3, 2, 1, 1)
        self.label_j_1_a_7 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_a_7.setObjectName(_fromUtf8("label_j_1_a_7"))
        self.gridLayout_3.addWidget(self.label_j_1_a_7, 0, 7, 1, 1)
        self.lcdNumber_j_1_a_0 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_a_0.setNumDigits(4)
        self.lcdNumber_j_1_a_0.setObjectName(_fromUtf8("lcdNumber_j_1_a_0"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_a_0, 2, 0, 1, 1)
        self.lcdNumber_j_1_a_7 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_a_7.setNumDigits(4)
        self.lcdNumber_j_1_a_7.setObjectName(_fromUtf8("lcdNumber_j_1_a_7"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_a_7, 2, 7, 1, 1)
        self.label_j_1_a_0 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_a_0.setObjectName(_fromUtf8("label_j_1_a_0"))
        self.gridLayout_3.addWidget(self.label_j_1_a_0, 0, 0, 1, 1)
        self.label_j_1_a_1 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_a_1.setObjectName(_fromUtf8("label_j_1_a_1"))
        self.gridLayout_3.addWidget(self.label_j_1_a_1, 0, 1, 1, 1)
        self.label_j_1_a_2 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_a_2.setObjectName(_fromUtf8("label_j_1_a_2"))
        self.gridLayout_3.addWidget(self.label_j_1_a_2, 0, 2, 1, 1)
        self.label_j_1_a_3 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_a_3.setObjectName(_fromUtf8("label_j_1_a_3"))
        self.gridLayout_3.addWidget(self.label_j_1_a_3, 0, 3, 1, 1)
        self.label_j_1_a_4 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_a_4.setObjectName(_fromUtf8("label_j_1_a_4"))
        self.gridLayout_3.addWidget(self.label_j_1_a_4, 0, 4, 1, 1)
        self.label_j_1_a_5 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_a_5.setObjectName(_fromUtf8("label_j_1_a_5"))
        self.gridLayout_3.addWidget(self.label_j_1_a_5, 0, 5, 1, 1)
        self.label_j_1_a_6 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_a_6.setObjectName(_fromUtf8("label_j_1_a_6"))
        self.gridLayout_3.addWidget(self.label_j_1_a_6, 0, 6, 1, 1)
        self.label_j_1_s_0 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_s_0.setObjectName(_fromUtf8("label_j_1_s_0"))
        self.gridLayout_3.addWidget(self.label_j_1_s_0, 3, 0, 1, 1)
        self.label_j_1_s_1 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_s_1.setObjectName(_fromUtf8("label_j_1_s_1"))
        self.gridLayout_3.addWidget(self.label_j_1_s_1, 3, 1, 1, 1)
        self.lcdNumber_j_1_a_5 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_a_5.setNumDigits(4)
        self.lcdNumber_j_1_a_5.setObjectName(_fromUtf8("lcdNumber_j_1_a_5"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_a_5, 2, 5, 1, 1)
        self.verticalSlider_j_1_a_1 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_a_1.setMinimum(-100)
        self.verticalSlider_j_1_a_1.setMaximum(100)
        self.verticalSlider_j_1_a_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_a_1.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_a_1.setTickInterval(25)
        self.verticalSlider_j_1_a_1.setObjectName(_fromUtf8("verticalSlider_j_1_a_1"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_a_1, 1, 1, 1, 1)
        self.verticalSlider_j_1_a_3 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_a_3.setMinimum(-100)
        self.verticalSlider_j_1_a_3.setMaximum(100)
        self.verticalSlider_j_1_a_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_a_3.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_a_3.setTickInterval(25)
        self.verticalSlider_j_1_a_3.setObjectName(_fromUtf8("verticalSlider_j_1_a_3"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_a_3, 1, 3, 1, 1)
        self.verticalSlider_j_1_a_4 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_a_4.setMinimum(-100)
        self.verticalSlider_j_1_a_4.setMaximum(100)
        self.verticalSlider_j_1_a_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_a_4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_a_4.setTickInterval(25)
        self.verticalSlider_j_1_a_4.setObjectName(_fromUtf8("verticalSlider_j_1_a_4"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_a_4, 1, 4, 1, 1)
        self.verticalSlider_j_1_a_6 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_a_6.setMinimum(-100)
        self.verticalSlider_j_1_a_6.setMaximum(100)
        self.verticalSlider_j_1_a_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_a_6.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_a_6.setTickInterval(25)
        self.verticalSlider_j_1_a_6.setObjectName(_fromUtf8("verticalSlider_j_1_a_6"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_a_6, 1, 6, 1, 1)
        self.verticalSlider_j_1_a_5 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_a_5.setMinimum(-100)
        self.verticalSlider_j_1_a_5.setMaximum(100)
        self.verticalSlider_j_1_a_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_a_5.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_a_5.setTickInterval(25)
        self.verticalSlider_j_1_a_5.setObjectName(_fromUtf8("verticalSlider_j_1_a_5"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_a_5, 1, 5, 1, 1)
        self.verticalSlider_j_1_a_2 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_a_2.setMinimum(-100)
        self.verticalSlider_j_1_a_2.setMaximum(100)
        self.verticalSlider_j_1_a_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_a_2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_a_2.setTickInterval(25)
        self.verticalSlider_j_1_a_2.setObjectName(_fromUtf8("verticalSlider_j_1_a_2"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_a_2, 1, 2, 1, 1)
        self.verticalSlider_j_1_a_7 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_a_7.setMinimum(-100)
        self.verticalSlider_j_1_a_7.setMaximum(100)
        self.verticalSlider_j_1_a_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_a_7.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_a_7.setTickInterval(25)
        self.verticalSlider_j_1_a_7.setObjectName(_fromUtf8("verticalSlider_j_1_a_7"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_a_7, 1, 7, 1, 1)
        self.lcdNumber_j_1_a_6 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_a_6.setNumDigits(4)
        self.lcdNumber_j_1_a_6.setObjectName(_fromUtf8("lcdNumber_j_1_a_6"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_a_6, 2, 6, 1, 1)
        self.lcdNumber_j_1_a_3 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_a_3.setNumDigits(4)
        self.lcdNumber_j_1_a_3.setObjectName(_fromUtf8("lcdNumber_j_1_a_3"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_a_3, 2, 3, 1, 1)
        self.lcdNumber_j_1_a_2 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_a_2.setNumDigits(4)
        self.lcdNumber_j_1_a_2.setObjectName(_fromUtf8("lcdNumber_j_1_a_2"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_a_2, 2, 2, 1, 1)
        self.lcdNumber_j_1_a_1 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_a_1.setNumDigits(4)
        self.lcdNumber_j_1_a_1.setObjectName(_fromUtf8("lcdNumber_j_1_a_1"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_a_1, 2, 1, 1, 1)
        self.label_j_1_s_6 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_s_6.setObjectName(_fromUtf8("label_j_1_s_6"))
        self.gridLayout_3.addWidget(self.label_j_1_s_6, 3, 6, 1, 1)
        self.label_j_1_s_7 = QtGui.QLabel(self.groupBox_j1)
        self.label_j_1_s_7.setObjectName(_fromUtf8("label_j_1_s_7"))
        self.gridLayout_3.addWidget(self.label_j_1_s_7, 3, 7, 1, 1)
        self.verticalSlider_j_1_s_1 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_s_1.setMinimum(-100)
        self.verticalSlider_j_1_s_1.setMaximum(100)
        self.verticalSlider_j_1_s_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_s_1.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_s_1.setTickInterval(25)
        self.verticalSlider_j_1_s_1.setObjectName(_fromUtf8("verticalSlider_j_1_s_1"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_s_1, 4, 1, 1, 1)
        self.verticalSlider_j_1_s_2 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_s_2.setMinimum(-100)
        self.verticalSlider_j_1_s_2.setMaximum(100)
        self.verticalSlider_j_1_s_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_s_2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_s_2.setTickInterval(25)
        self.verticalSlider_j_1_s_2.setObjectName(_fromUtf8("verticalSlider_j_1_s_2"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_s_2, 4, 2, 1, 1)
        self.verticalSlider_j_1_s_3 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_s_3.setMinimum(-100)
        self.verticalSlider_j_1_s_3.setMaximum(100)
        self.verticalSlider_j_1_s_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_s_3.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_s_3.setTickInterval(25)
        self.verticalSlider_j_1_s_3.setObjectName(_fromUtf8("verticalSlider_j_1_s_3"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_s_3, 4, 3, 1, 1)
        self.verticalSlider_j_1_s_4 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_s_4.setMinimum(-100)
        self.verticalSlider_j_1_s_4.setMaximum(100)
        self.verticalSlider_j_1_s_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_s_4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_s_4.setTickInterval(25)
        self.verticalSlider_j_1_s_4.setObjectName(_fromUtf8("verticalSlider_j_1_s_4"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_s_4, 4, 4, 1, 1)
        self.verticalSlider_j_1_s_5 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_s_5.setMinimum(-100)
        self.verticalSlider_j_1_s_5.setMaximum(100)
        self.verticalSlider_j_1_s_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_s_5.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_s_5.setTickInterval(25)
        self.verticalSlider_j_1_s_5.setObjectName(_fromUtf8("verticalSlider_j_1_s_5"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_s_5, 4, 5, 1, 1)
        self.verticalSlider_j_1_s_6 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_s_6.setMinimum(-100)
        self.verticalSlider_j_1_s_6.setMaximum(100)
        self.verticalSlider_j_1_s_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_s_6.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_s_6.setTickInterval(25)
        self.verticalSlider_j_1_s_6.setObjectName(_fromUtf8("verticalSlider_j_1_s_6"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_s_6, 4, 6, 1, 1)
        self.verticalSlider_j_1_s_7 = QtGui.QSlider(self.groupBox_j1)
        self.verticalSlider_j_1_s_7.setMinimum(-100)
        self.verticalSlider_j_1_s_7.setMaximum(100)
        self.verticalSlider_j_1_s_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_j_1_s_7.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_j_1_s_7.setTickInterval(25)
        self.verticalSlider_j_1_s_7.setObjectName(_fromUtf8("verticalSlider_j_1_s_7"))
        self.gridLayout_3.addWidget(self.verticalSlider_j_1_s_7, 4, 7, 1, 1)
        self.lcdNumber_j_1_s_7 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_s_7.setNumDigits(4)
        self.lcdNumber_j_1_s_7.setObjectName(_fromUtf8("lcdNumber_j_1_s_7"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_s_7, 5, 7, 1, 1)
        self.lcdNumber_j_1_s_6 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_s_6.setNumDigits(4)
        self.lcdNumber_j_1_s_6.setObjectName(_fromUtf8("lcdNumber_j_1_s_6"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_s_6, 5, 6, 1, 1)
        self.lcdNumber_j_1_s_5 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_s_5.setNumDigits(4)
        self.lcdNumber_j_1_s_5.setObjectName(_fromUtf8("lcdNumber_j_1_s_5"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_s_5, 5, 5, 1, 1)
        self.lcdNumber_j_1_s_4 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_s_4.setNumDigits(4)
        self.lcdNumber_j_1_s_4.setObjectName(_fromUtf8("lcdNumber_j_1_s_4"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_s_4, 5, 4, 1, 1)
        self.lcdNumber_j_1_s_3 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_s_3.setNumDigits(4)
        self.lcdNumber_j_1_s_3.setObjectName(_fromUtf8("lcdNumber_j_1_s_3"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_s_3, 5, 3, 1, 1)
        self.lcdNumber_j_1_s_2 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_s_2.setNumDigits(4)
        self.lcdNumber_j_1_s_2.setObjectName(_fromUtf8("lcdNumber_j_1_s_2"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_s_2, 5, 2, 1, 1)
        self.lcdNumber_j_1_s_1 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_s_1.setNumDigits(4)
        self.lcdNumber_j_1_s_1.setObjectName(_fromUtf8("lcdNumber_j_1_s_1"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_s_1, 5, 1, 1, 1)
        self.lcdNumber_j_1_s_0 = QtGui.QLCDNumber(self.groupBox_j1)
        self.lcdNumber_j_1_s_0.setNumDigits(4)
        self.lcdNumber_j_1_s_0.setObjectName(_fromUtf8("lcdNumber_j_1_s_0"))
        self.gridLayout_3.addWidget(self.lcdNumber_j_1_s_0, 5, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.groupBox_j1, 1, 2, 1, 1)
        self.groupBox_channels = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_channels.setObjectName(_fromUtf8("groupBox_channels"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_channels)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lineEdit_ch_0 = QtGui.QLineEdit(self.groupBox_channels)
        self.lineEdit_ch_0.setObjectName(_fromUtf8("lineEdit_ch_0"))
        self.gridLayout_4.addWidget(self.lineEdit_ch_0, 4, 0, 1, 1)
        self.verticalSlider_ch_0 = QtGui.QSlider(self.groupBox_channels)
        self.verticalSlider_ch_0.setMinimum(-200)
        self.verticalSlider_ch_0.setMaximum(200)
        self.verticalSlider_ch_0.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_ch_0.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_ch_0.setTickInterval(25)
        self.verticalSlider_ch_0.setObjectName(_fromUtf8("verticalSlider_ch_0"))
        self.gridLayout_4.addWidget(self.verticalSlider_ch_0, 2, 0, 1, 1)
        self.label_ch_0 = QtGui.QLabel(self.groupBox_channels)
        self.label_ch_0.setObjectName(_fromUtf8("label_ch_0"))
        self.gridLayout_4.addWidget(self.label_ch_0, 1, 0, 1, 1)
        self.lcdNumber_ch_0 = QtGui.QLCDNumber(self.groupBox_channels)
        self.lcdNumber_ch_0.setNumDigits(4)
        self.lcdNumber_ch_0.setObjectName(_fromUtf8("lcdNumber_ch_0"))
        self.gridLayout_4.addWidget(self.lcdNumber_ch_0, 3, 0, 1, 1)
        self.lineEdit_ch_5 = QtGui.QLineEdit(self.groupBox_channels)
        self.lineEdit_ch_5.setObjectName(_fromUtf8("lineEdit_ch_5"))
        self.gridLayout_4.addWidget(self.lineEdit_ch_5, 4, 5, 1, 1)
        self.verticalSlider_ch_1 = QtGui.QSlider(self.groupBox_channels)
        self.verticalSlider_ch_1.setMinimum(-200)
        self.verticalSlider_ch_1.setMaximum(200)
        self.verticalSlider_ch_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_ch_1.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_ch_1.setTickInterval(25)
        self.verticalSlider_ch_1.setObjectName(_fromUtf8("verticalSlider_ch_1"))
        self.gridLayout_4.addWidget(self.verticalSlider_ch_1, 2, 1, 1, 1)
        self.verticalSlider_ch_2 = QtGui.QSlider(self.groupBox_channels)
        self.verticalSlider_ch_2.setMinimum(-200)
        self.verticalSlider_ch_2.setMaximum(200)
        self.verticalSlider_ch_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_ch_2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_ch_2.setTickInterval(25)
        self.verticalSlider_ch_2.setObjectName(_fromUtf8("verticalSlider_ch_2"))
        self.gridLayout_4.addWidget(self.verticalSlider_ch_2, 2, 2, 1, 1)
        self.lineEdit_ch_1 = QtGui.QLineEdit(self.groupBox_channels)
        self.lineEdit_ch_1.setObjectName(_fromUtf8("lineEdit_ch_1"))
        self.gridLayout_4.addWidget(self.lineEdit_ch_1, 4, 1, 1, 1)
        self.lineEdit_ch_4 = QtGui.QLineEdit(self.groupBox_channels)
        self.lineEdit_ch_4.setObjectName(_fromUtf8("lineEdit_ch_4"))
        self.gridLayout_4.addWidget(self.lineEdit_ch_4, 4, 4, 1, 1)
        self.lineEdit_ch_7 = QtGui.QLineEdit(self.groupBox_channels)
        self.lineEdit_ch_7.setObjectName(_fromUtf8("lineEdit_ch_7"))
        self.gridLayout_4.addWidget(self.lineEdit_ch_7, 4, 7, 1, 1)
        self.lineEdit_ch_6 = QtGui.QLineEdit(self.groupBox_channels)
        self.lineEdit_ch_6.setObjectName(_fromUtf8("lineEdit_ch_6"))
        self.gridLayout_4.addWidget(self.lineEdit_ch_6, 4, 6, 1, 1)
        self.lineEdit_ch_3 = QtGui.QLineEdit(self.groupBox_channels)
        self.lineEdit_ch_3.setObjectName(_fromUtf8("lineEdit_ch_3"))
        self.gridLayout_4.addWidget(self.lineEdit_ch_3, 4, 3, 1, 1)
        self.verticalSlider_ch_3 = QtGui.QSlider(self.groupBox_channels)
        self.verticalSlider_ch_3.setMinimum(-200)
        self.verticalSlider_ch_3.setMaximum(200)
        self.verticalSlider_ch_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_ch_3.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_ch_3.setTickInterval(25)
        self.verticalSlider_ch_3.setObjectName(_fromUtf8("verticalSlider_ch_3"))
        self.gridLayout_4.addWidget(self.verticalSlider_ch_3, 2, 3, 1, 1)
        self.lineEdit_ch_2 = QtGui.QLineEdit(self.groupBox_channels)
        self.lineEdit_ch_2.setObjectName(_fromUtf8("lineEdit_ch_2"))
        self.gridLayout_4.addWidget(self.lineEdit_ch_2, 4, 2, 1, 1)
        self.verticalSlider_ch_4 = QtGui.QSlider(self.groupBox_channels)
        self.verticalSlider_ch_4.setMinimum(-200)
        self.verticalSlider_ch_4.setMaximum(200)
        self.verticalSlider_ch_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_ch_4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_ch_4.setTickInterval(25)
        self.verticalSlider_ch_4.setObjectName(_fromUtf8("verticalSlider_ch_4"))
        self.gridLayout_4.addWidget(self.verticalSlider_ch_4, 2, 4, 1, 1)
        self.verticalSlider_ch_5 = QtGui.QSlider(self.groupBox_channels)
        self.verticalSlider_ch_5.setMinimum(-200)
        self.verticalSlider_ch_5.setMaximum(200)
        self.verticalSlider_ch_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_ch_5.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_ch_5.setTickInterval(25)
        self.verticalSlider_ch_5.setObjectName(_fromUtf8("verticalSlider_ch_5"))
        self.gridLayout_4.addWidget(self.verticalSlider_ch_5, 2, 5, 1, 1)
        self.verticalSlider_ch_6 = QtGui.QSlider(self.groupBox_channels)
        self.verticalSlider_ch_6.setMinimum(-200)
        self.verticalSlider_ch_6.setMaximum(200)
        self.verticalSlider_ch_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_ch_6.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_ch_6.setTickInterval(25)
        self.verticalSlider_ch_6.setObjectName(_fromUtf8("verticalSlider_ch_6"))
        self.gridLayout_4.addWidget(self.verticalSlider_ch_6, 2, 6, 1, 1)
        self.verticalSlider_ch_7 = QtGui.QSlider(self.groupBox_channels)
        self.verticalSlider_ch_7.setMinimum(-200)
        self.verticalSlider_ch_7.setMaximum(200)
        self.verticalSlider_ch_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_ch_7.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider_ch_7.setTickInterval(25)
        self.verticalSlider_ch_7.setObjectName(_fromUtf8("verticalSlider_ch_7"))
        self.gridLayout_4.addWidget(self.verticalSlider_ch_7, 2, 7, 1, 1)
        self.lcdNumber_ch_7 = QtGui.QLCDNumber(self.groupBox_channels)
        self.lcdNumber_ch_7.setNumDigits(4)
        self.lcdNumber_ch_7.setObjectName(_fromUtf8("lcdNumber_ch_7"))
        self.gridLayout_4.addWidget(self.lcdNumber_ch_7, 3, 7, 1, 1)
        self.lcdNumber_ch_6 = QtGui.QLCDNumber(self.groupBox_channels)
        self.lcdNumber_ch_6.setNumDigits(4)
        self.lcdNumber_ch_6.setObjectName(_fromUtf8("lcdNumber_ch_6"))
        self.gridLayout_4.addWidget(self.lcdNumber_ch_6, 3, 6, 1, 1)
        self.lcdNumber_ch_5 = QtGui.QLCDNumber(self.groupBox_channels)
        self.lcdNumber_ch_5.setNumDigits(4)
        self.lcdNumber_ch_5.setObjectName(_fromUtf8("lcdNumber_ch_5"))
        self.gridLayout_4.addWidget(self.lcdNumber_ch_5, 3, 5, 1, 1)
        self.lcdNumber_ch_4 = QtGui.QLCDNumber(self.groupBox_channels)
        self.lcdNumber_ch_4.setNumDigits(4)
        self.lcdNumber_ch_4.setObjectName(_fromUtf8("lcdNumber_ch_4"))
        self.gridLayout_4.addWidget(self.lcdNumber_ch_4, 3, 4, 1, 1)
        self.lcdNumber_ch_3 = QtGui.QLCDNumber(self.groupBox_channels)
        self.lcdNumber_ch_3.setNumDigits(4)
        self.lcdNumber_ch_3.setObjectName(_fromUtf8("lcdNumber_ch_3"))
        self.gridLayout_4.addWidget(self.lcdNumber_ch_3, 3, 3, 1, 1)
        self.lcdNumber_ch_2 = QtGui.QLCDNumber(self.groupBox_channels)
        self.lcdNumber_ch_2.setNumDigits(4)
        self.lcdNumber_ch_2.setObjectName(_fromUtf8("lcdNumber_ch_2"))
        self.gridLayout_4.addWidget(self.lcdNumber_ch_2, 3, 2, 1, 1)
        self.label_ch_7 = QtGui.QLabel(self.groupBox_channels)
        self.label_ch_7.setObjectName(_fromUtf8("label_ch_7"))
        self.gridLayout_4.addWidget(self.label_ch_7, 1, 7, 1, 1)
        self.label_ch_6 = QtGui.QLabel(self.groupBox_channels)
        self.label_ch_6.setObjectName(_fromUtf8("label_ch_6"))
        self.gridLayout_4.addWidget(self.label_ch_6, 1, 6, 1, 1)
        self.label_ch_5 = QtGui.QLabel(self.groupBox_channels)
        self.label_ch_5.setObjectName(_fromUtf8("label_ch_5"))
        self.gridLayout_4.addWidget(self.label_ch_5, 1, 5, 1, 1)
        self.label_ch_4 = QtGui.QLabel(self.groupBox_channels)
        self.label_ch_4.setObjectName(_fromUtf8("label_ch_4"))
        self.gridLayout_4.addWidget(self.label_ch_4, 1, 4, 1, 1)
        self.label_ch_3 = QtGui.QLabel(self.groupBox_channels)
        self.label_ch_3.setObjectName(_fromUtf8("label_ch_3"))
        self.gridLayout_4.addWidget(self.label_ch_3, 1, 3, 1, 1)
        self.label_ch_2 = QtGui.QLabel(self.groupBox_channels)
        self.label_ch_2.setObjectName(_fromUtf8("label_ch_2"))
        self.gridLayout_4.addWidget(self.label_ch_2, 1, 2, 1, 1)
        self.label_ch_1 = QtGui.QLabel(self.groupBox_channels)
        self.label_ch_1.setObjectName(_fromUtf8("label_ch_1"))
        self.gridLayout_4.addWidget(self.label_ch_1, 1, 1, 1, 1)
        self.lcdNumber_ch_1 = QtGui.QLCDNumber(self.groupBox_channels)
        self.lcdNumber_ch_1.setNumDigits(4)
        self.lcdNumber_ch_1.setObjectName(_fromUtf8("lcdNumber_ch_1"))
        self.gridLayout_4.addWidget(self.lcdNumber_ch_1, 3, 1, 1, 1)
        self.comboBox_preset = QtGui.QComboBox(self.groupBox_channels)
        self.comboBox_preset.setEditable(True)
        self.comboBox_preset.setObjectName(_fromUtf8("comboBox_preset"))
        self.gridLayout_4.addWidget(self.comboBox_preset, 0, 3, 1, 5)
        self.pushButton_save = QtGui.QPushButton(self.groupBox_channels)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.gridLayout_4.addWidget(self.pushButton_save, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_channels, 2, 1, 1, 2)
        self.gridLayout.setRowStretch(1, 3)
        self.gridLayout.setRowStretch(2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.verticalSlider_j_0_a_0, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_a_0.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_a_1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_a_1.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_a_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_a_2.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_a_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_a_3.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_a_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_a_4.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_a_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_a_5.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_a_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_a_6.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_a_7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_a_7.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_s_0, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_s_0.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_s_1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_s_1.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_s_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_s_2.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_s_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_s_3.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_s_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_s_4.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_s_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_s_5.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_s_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_s_6.display)
        QtCore.QObject.connect(self.verticalSlider_j_0_s_7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_0_s_7.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_a_0, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_a_0.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_a_1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_a_1.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_a_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_a_2.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_a_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_a_3.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_a_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_a_4.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_a_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_a_5.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_a_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_a_6.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_a_7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_a_7.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_s_0, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_s_0.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_s_1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_s_1.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_s_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_s_2.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_s_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_s_3.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_s_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_s_4.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_s_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_s_5.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_s_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_s_6.display)
        QtCore.QObject.connect(self.verticalSlider_j_1_s_7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_j_1_s_7.display)
        QtCore.QObject.connect(self.verticalSlider_ch_0, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_ch_0.display)
        QtCore.QObject.connect(self.verticalSlider_ch_1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_ch_1.display)
        QtCore.QObject.connect(self.verticalSlider_ch_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_ch_2.display)
        QtCore.QObject.connect(self.verticalSlider_ch_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_ch_3.display)
        QtCore.QObject.connect(self.verticalSlider_ch_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_ch_4.display)
        QtCore.QObject.connect(self.verticalSlider_ch_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_ch_5.display)
        QtCore.QObject.connect(self.verticalSlider_ch_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_ch_6.display)
        QtCore.QObject.connect(self.verticalSlider_ch_7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_ch_7.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.verticalSlider_j_0_a_0, self.verticalSlider_j_0_a_1)
        MainWindow.setTabOrder(self.verticalSlider_j_0_a_1, self.verticalSlider_j_0_a_2)
        MainWindow.setTabOrder(self.verticalSlider_j_0_a_2, self.verticalSlider_j_0_a_3)
        MainWindow.setTabOrder(self.verticalSlider_j_0_a_3, self.verticalSlider_j_0_a_4)
        MainWindow.setTabOrder(self.verticalSlider_j_0_a_4, self.verticalSlider_j_0_a_5)
        MainWindow.setTabOrder(self.verticalSlider_j_0_a_5, self.verticalSlider_j_0_a_6)
        MainWindow.setTabOrder(self.verticalSlider_j_0_a_6, self.verticalSlider_j_0_a_7)
        MainWindow.setTabOrder(self.verticalSlider_j_0_a_7, self.verticalSlider_j_0_s_0)
        MainWindow.setTabOrder(self.verticalSlider_j_0_s_0, self.verticalSlider_j_0_s_1)
        MainWindow.setTabOrder(self.verticalSlider_j_0_s_1, self.verticalSlider_j_0_s_2)
        MainWindow.setTabOrder(self.verticalSlider_j_0_s_2, self.verticalSlider_j_0_s_3)
        MainWindow.setTabOrder(self.verticalSlider_j_0_s_3, self.verticalSlider_j_0_s_4)
        MainWindow.setTabOrder(self.verticalSlider_j_0_s_4, self.verticalSlider_j_0_s_5)
        MainWindow.setTabOrder(self.verticalSlider_j_0_s_5, self.verticalSlider_j_0_s_6)
        MainWindow.setTabOrder(self.verticalSlider_j_0_s_6, self.verticalSlider_j_0_s_7)
        MainWindow.setTabOrder(self.verticalSlider_j_0_s_7, self.verticalSlider_j_1_a_0)
        MainWindow.setTabOrder(self.verticalSlider_j_1_a_0, self.verticalSlider_j_1_a_1)
        MainWindow.setTabOrder(self.verticalSlider_j_1_a_1, self.verticalSlider_j_1_a_2)
        MainWindow.setTabOrder(self.verticalSlider_j_1_a_2, self.verticalSlider_j_1_a_3)
        MainWindow.setTabOrder(self.verticalSlider_j_1_a_3, self.verticalSlider_j_1_a_4)
        MainWindow.setTabOrder(self.verticalSlider_j_1_a_4, self.verticalSlider_j_1_a_5)
        MainWindow.setTabOrder(self.verticalSlider_j_1_a_5, self.verticalSlider_j_1_a_6)
        MainWindow.setTabOrder(self.verticalSlider_j_1_a_6, self.verticalSlider_j_1_a_7)
        MainWindow.setTabOrder(self.verticalSlider_j_1_a_7, self.verticalSlider_j_1_s_0)
        MainWindow.setTabOrder(self.verticalSlider_j_1_s_0, self.verticalSlider_j_1_s_1)
        MainWindow.setTabOrder(self.verticalSlider_j_1_s_1, self.verticalSlider_j_1_s_2)
        MainWindow.setTabOrder(self.verticalSlider_j_1_s_2, self.verticalSlider_j_1_s_3)
        MainWindow.setTabOrder(self.verticalSlider_j_1_s_3, self.verticalSlider_j_1_s_4)
        MainWindow.setTabOrder(self.verticalSlider_j_1_s_4, self.verticalSlider_j_1_s_5)
        MainWindow.setTabOrder(self.verticalSlider_j_1_s_5, self.verticalSlider_j_1_s_6)
        MainWindow.setTabOrder(self.verticalSlider_j_1_s_6, self.verticalSlider_j_1_s_7)
        MainWindow.setTabOrder(self.verticalSlider_j_1_s_7, self.verticalSlider_ch_0)
        MainWindow.setTabOrder(self.verticalSlider_ch_0, self.verticalSlider_ch_1)
        MainWindow.setTabOrder(self.verticalSlider_ch_1, self.verticalSlider_ch_2)
        MainWindow.setTabOrder(self.verticalSlider_ch_2, self.verticalSlider_ch_3)
        MainWindow.setTabOrder(self.verticalSlider_ch_3, self.verticalSlider_ch_4)
        MainWindow.setTabOrder(self.verticalSlider_ch_4, self.verticalSlider_ch_5)
        MainWindow.setTabOrder(self.verticalSlider_ch_5, self.verticalSlider_ch_6)
        MainWindow.setTabOrder(self.verticalSlider_ch_6, self.verticalSlider_ch_7)
        MainWindow.setTabOrder(self.verticalSlider_ch_7, self.lineEdit_ch_0)
        MainWindow.setTabOrder(self.lineEdit_ch_0, self.lineEdit_ch_1)
        MainWindow.setTabOrder(self.lineEdit_ch_1, self.lineEdit_ch_2)
        MainWindow.setTabOrder(self.lineEdit_ch_2, self.lineEdit_ch_3)
        MainWindow.setTabOrder(self.lineEdit_ch_3, self.lineEdit_ch_4)
        MainWindow.setTabOrder(self.lineEdit_ch_4, self.lineEdit_ch_5)
        MainWindow.setTabOrder(self.lineEdit_ch_5, self.lineEdit_ch_6)
        MainWindow.setTabOrder(self.lineEdit_ch_6, self.lineEdit_ch_7)
        MainWindow.setTabOrder(self.lineEdit_ch_7, self.comboBox_preset)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MAVLinkRemote", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_j0.setTitle(QtGui.QApplication.translate("MainWindow", "Joystick 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_a_7.setText(QtGui.QApplication.translate("MainWindow", "j0a7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_a_0.setText(QtGui.QApplication.translate("MainWindow", "j0a0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_a_1.setText(QtGui.QApplication.translate("MainWindow", "j0a1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_a_2.setText(QtGui.QApplication.translate("MainWindow", "j0a2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_a_3.setText(QtGui.QApplication.translate("MainWindow", "j0a3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_a_4.setText(QtGui.QApplication.translate("MainWindow", "j0a4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_a_5.setText(QtGui.QApplication.translate("MainWindow", "j0a5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_a_6.setText(QtGui.QApplication.translate("MainWindow", "j0a6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_s_0.setText(QtGui.QApplication.translate("MainWindow", "j0s0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_s_1.setText(QtGui.QApplication.translate("MainWindow", "j0s1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_s_2.setText(QtGui.QApplication.translate("MainWindow", "j0s2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_s_3.setText(QtGui.QApplication.translate("MainWindow", "j0s3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_s_4.setText(QtGui.QApplication.translate("MainWindow", "j0s4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_s_5.setText(QtGui.QApplication.translate("MainWindow", "j0s5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_s_6.setText(QtGui.QApplication.translate("MainWindow", "j0s6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_0_s_7.setText(QtGui.QApplication.translate("MainWindow", "j0s7", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_j1.setTitle(QtGui.QApplication.translate("MainWindow", "Joystick 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_s_5.setText(QtGui.QApplication.translate("MainWindow", "j1s5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_s_3.setText(QtGui.QApplication.translate("MainWindow", "j1s3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_s_4.setText(QtGui.QApplication.translate("MainWindow", "j1s4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_s_2.setText(QtGui.QApplication.translate("MainWindow", "j1s2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_a_7.setText(QtGui.QApplication.translate("MainWindow", "j1a7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_a_0.setText(QtGui.QApplication.translate("MainWindow", "j1a0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_a_1.setText(QtGui.QApplication.translate("MainWindow", "j1a1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_a_2.setText(QtGui.QApplication.translate("MainWindow", "j1a2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_a_3.setText(QtGui.QApplication.translate("MainWindow", "j1a3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_a_4.setText(QtGui.QApplication.translate("MainWindow", "j1a4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_a_5.setText(QtGui.QApplication.translate("MainWindow", "j1a5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_a_6.setText(QtGui.QApplication.translate("MainWindow", "j1a6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_s_0.setText(QtGui.QApplication.translate("MainWindow", "j1s0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_s_1.setText(QtGui.QApplication.translate("MainWindow", "j1s1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_s_6.setText(QtGui.QApplication.translate("MainWindow", "j1s6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_j_1_s_7.setText(QtGui.QApplication.translate("MainWindow", "j1s7", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_channels.setTitle(QtGui.QApplication.translate("MainWindow", "Output Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ch_0.setText(QtGui.QApplication.translate("MainWindow", "ch0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ch_7.setText(QtGui.QApplication.translate("MainWindow", "ch7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ch_6.setText(QtGui.QApplication.translate("MainWindow", "ch6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ch_5.setText(QtGui.QApplication.translate("MainWindow", "ch5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ch_4.setText(QtGui.QApplication.translate("MainWindow", "ch4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ch_3.setText(QtGui.QApplication.translate("MainWindow", "ch3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ch_2.setText(QtGui.QApplication.translate("MainWindow", "ch2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ch_1.setText(QtGui.QApplication.translate("MainWindow", "ch1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setText(QtGui.QApplication.translate("MainWindow", "save state", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
